version: "4"
name: dotnet_ultimate
services:
  postgres:
    container_name: postgres_dotnet_ultimate
    image: postgres:15-alpine
    networks:
      - dotnet_ultimate
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
      - PGPORT=5433
    ports:
      - 5433:5433
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgadmin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresdata:

networks:
  dotnet_ultimate:
    name: dotnet_ultimate