// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dotnet_ultimate.Persistence;

#nullable disable

namespace dotnet_ultimate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240908133514_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dotnet_ultimate.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Apple's latest flagship smartphone with a ProMotion display and improved cameras",
                            Name = "iPhone 15 Pro",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dell's high-performance laptop with a 4K InfinityEdge display",
                            Name = "Dell XPS 15",
                            Price = 1899.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sony's top-of-the-line wireless noise-canceling headphones",
                            Name = "Sony WH-1000XM4",
                            Price = 349.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
